#!/bin/sh
curDir=`pwd |awk -F'[/]' '{print $NF}'`
if [ $curDir = "exec" ]; then
cobc -g -x -v -fnull-param ./${1}.cob ../lib/screenDescription.c ../lib/MultiThread.c ../lib/printDescription.c ../lib/cob-mysql.c ../lib/C3_LIBRARY.c ../lib/C_LIBRARY.c `xml2-config --cflags --libs` -lhpdf `mariadb_config  --include --libs` -I../lib
else
    echo '正しいフォルダで行ってください'
fi
