#!/bin/sh
curDir=`pwd |awk -F'[/]' '{print $NF}'`
#targDir=/var/www/html/source/exec
targDir=.
if [ $curDir = "exec" ]; then
cobc -x -fnull-param -v -g -o ${targDir}/${1} ./${1}.cob /usr/local/lib/map/*.c `xml2-config --cflags --libs` -lhpdf `mariadb_config --include --libs` -I../lib
else
    echo '正しいフォルダで行ってください'
fi
