#!/bin/sh
curDir=`pwd |awk -F'[/]' '{print $NF}'`
if [ $curDir = "exec" ]; then
cobc -x -fnull-param ./${1}.cob /usr/local/lib/map/*.c `xml2-config --cflags --libs` -lhpdf `mysql_config --include --libs` -I../lib
else
    echo '正しいフォルダで行ってください'
fi
