#!/bin/tcsh
if (${#argv} >= 1) then
    set USER_ID = ${argv[1]};
else
    set USER_ID = STN000;
endif
set JRCODE=000;
set FN1 = ${JRCODE_PATH}${USER_ID};
set FN2 = ${ERROR_PATH}${USER_ID};
set ABORT=0;
../exec/JT600U $USER_ID $JRCODE
source ../job/CRC_LIBRARY.sh
if($JRCODE == 000) then
  goto ENDJOB
endif
if($JRCODE == 255) then
  goto ENDJOB
endif
if($ABORT == 1) then
  goto ENDJOB
endif
FLCNV 'IDE=NO ODE=MSD OCI= OFI=T-CHKF OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D001 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1001 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3001 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D002 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1002 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3002 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D003 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1003 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3003 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D004 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1004 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3004 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D005 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1005 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3005 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D006 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1006 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3006 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D007 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1007 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3007 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D008 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1008 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3008 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D009 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1009 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3009 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D010 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1010 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3010 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D011 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1011 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3011 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D012 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1012 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3012 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D013 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1013 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3013 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D014 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1014 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3014 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D015 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1015 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3015 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D016 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1016 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3016 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D017 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1017 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3017 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D018 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1018 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3018 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D019 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1019 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3019 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D020 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1020 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3020 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D021 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1021 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3021 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D022 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1022 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3022 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D023 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1023 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3023 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D024 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1024 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3024 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D025 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1025 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3025 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D026 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1026 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3026 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D027 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1027 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3027 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D028 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1028 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3028 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D029 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1029 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3029 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D030 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1030 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3030 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D031 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1031 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3031 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D032 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1032 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3032 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D033 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1033 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3033 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D034 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1034 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3034 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D035 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1035 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3035 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D036 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1036 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3036 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D037 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1037 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3037 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D038 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1038 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3038 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D039 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1039 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3039 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D040 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1040 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3040 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D041 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1041 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3041 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D042 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1042 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3042 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D043 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1043 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3043 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D044 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1044 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3044 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D045 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1045 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3045 OGN= CMD=BOTH CLR=NO SAV= NXT='
source ../job/CRC_LIBRARY.sh
ENDJOB:
