#!/bin/tcsh
if (${#argv} >= 1) then
    set USER_ID = ${argv[1]};
else
    set USER_ID = STN000;
endif
set JRCODE=000;
set FN1 = ${JRCODE_PATH}${USER_ID};
set FN2 = ${ERROR_PATH}${USER_ID};
set ABORT=0;
../exec/JT600U $USER_ID $JRCODE 1
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D001 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1001 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3001 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D002 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1002 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3002 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D003 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1003 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3003 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D004 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1004 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3004 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D005 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1005 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3005 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D006 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1006 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3006 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D007 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1007 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3007 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D008 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1008 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3008 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D009 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1009 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3009 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D010 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1010 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3010 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D011 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1011 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3011 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D012 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1012 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3012 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D013 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1013 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3013 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D014 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1014 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3014 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D015 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1015 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3015 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D016 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1016 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3016 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D017 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1017 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3017 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D018 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1018 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3018 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D019 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1019 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3019 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D020 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1020 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3020 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D021 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1021 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3021 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D022 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1022 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3022 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D023 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1023 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3023 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D024 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1024 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3024 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170D025 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K1025 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
FLCNV 'IDE=NO ODE=MSD OCI= OFI=JT-W170K3025 OGN= CMD=BOTH CLR=NO SAV= NXT= '
source ../job/CRC_LIBRARY.sh
ENDJOB:
