#!/bin/tcsh
source ../job/RC_INIT.sh
set ABORT=0;
FLCNV 'IDE=MSD ICI= IFI=TUKOF IGN= IFO=PROTECT ODE=MSD OCI= OFI=TUKFW OGN= LST=NO ERR=ABORT MOD=CREATE AMD=PHYSICAL CMD=BOTH GTR= DEL=NO CLR=NO OUT= RNG= SEL= SAV= NXT= '
source ../job/CRC_LIBRARY.sh
if($ABORT == 1) then
  goto ENDJOB
endif
set ABORT=0;
FLCNV 'IDE=MSD ICI= IFI=TUKF1 IGN= IFO=PROTECT ODE=MSD OCI= OFI=TUKFW OGN= LST=NO ERR=ABORT MOD=ADD AMD=LOGICAL CMD=BOTH GTR= DEL=NO CLR=NO OUT= RNG= SEL= SAV= NXT= '
source ../job/CRC_LIBRARY.sh
if($ABORT == 1) then
  goto ENDJOB
endif
set ABORT=0
../exec/NSM01U $USER_ID $JRCODE
source ../job/CRC_LIBRARY.sh
if($ABORT == 1) then
  goto ENDJOB
endif
if($JRCODE == 255) then
  goto ENDJOB
endif
#/RUN #MIXGN,DEV=MSD,SIZ=16;
#ACT=ALIGN_KDE=MSD_KCI=_KFI=NFTORI-D_WKD=TEMPORARY_WPB=YES_SKO=NO_LST=NO_
#SAV=_NXT=_
#/> ;
#/: ABORT JUMP=ENDJOB;
set ABORT=0
../exec/NSM02U $USER_ID $JRCODE
source ../job/CRC_LIBRARY.sh
if($ABORT == 1) then
  goto ENDJOB
endif
if($JRCODE == 255) then
  goto ENDJOB
endif
#/RUN #MIXGN,DEV=MSD,SIZ=16;
#ACT=ALIGN_KDE=MSD_KCI=_KFI=NFTORI-D_WKD=TEMPORARY_WPB=YES_SKO=NO_LST=NO_
#SAV=_NXT=_
#/> ;
#/: ABORT JUMP=ENDJOB;
set ABORT=0
../exec/NSM03U $USER_ID $JRCODE
source ../job/CRC_LIBRARY.sh
if($ABORT == 1) then
  goto ENDJOB
endif
#/RUN #MIXGN,DEV=MSD,SIZ=16;
#ACT=ALIGN_KDE=MSD_KCI=_KFI=NFTORI-D_WKD=TEMPORARY_WPB=YES_SKO=NO_LST=NO_
#SAV=_NXT=_
#/> ;
NFCNV 'MN1=C MN2=AD PA1=MSD PA2= PA3=NFTORI-D PA4=1 PA5=C5,J10,C17 \
PB1=../tmp/NFTORI.CSV PB2=CSV2 PB3=EXCLUSIVE PB4=COMMA PB7=C,J,C \
PB8=CREATE MN1=Q '
ENDJOB:
