#!/bin/tcsh
if (${#argv} >= 1) then
    set USER_ID = ${argv[1]};
else
    set USER_ID = STN000;
endif
set JRCODE=000;
set FN1 = ${JRCODE_PATH}${USER_ID};
set FN2 = ${ERROR_PATH}${USER_ID};
set ABORT=0;
../exec/JTN00U $USER_ID $JRCODE 2 1 1
source ../job/CRC_LIBRARY.sh
if($JRCODE == 255) then
  goto ENDJOB
endif
if($ABORT == 1) then
  goto ENDJOB
endif
#/ASSIGN OEFN=JOLSF,EFN=JOLSF-RYO;
#/ASSIGN OEFN=JSTR,EFN=JSTR-RYO;
#/ASSIGN OEFN=JNIF,EFN=JNIF-RYO;
#/ASSIGN OEFN=OKJF,EFN=OKJF-RYO;
#/ASSIGN OEFN=TDNWF,EFN=TDNWF-RYO;
#/ASSIGN OEFN=TDNNF,EFN=TDNNF-RYO;
#/ASSIGN OEFN=TDIF,EFN=TDIF-RYO;
#/ASSIGN OEFN=TDNAF,EFN=TDNAF-RYO;
setenv JOLSF "JOLSF-RYO"
setenv JSTR  "JSTR-RYO"
setenv JNIF  "JNIF-RYO"
setenv OKJF  "OKJF-RYO"
setenv TDNWF "TDNWF-RYO"
setenv TDNNF "TDNNF-RYO"
setenv TDIF  "TDIF-RYO"
setenv TDNAF "TDNAF-RYO"
set ABORT=0;
../exec/JK020U $USER_ID $JRCODE 1
source ../job/CRC_LIBRARY.sh
#/ASSIGN OEFN=JOLSF,RESOURCE=RELEASE;
#/ASSIGN OEFN=JSTR,RESOURCE=RELEASE;
#/ASSIGN OEFN=JNIF,RESOURCE=RELEASE;
#/ASSIGN OEFN=OKJF,RESOURCE=RELEASE;
#/ASSIGN OEFN=TDNWF,RESOURCE=RELEASE;
#/ASSIGN OEFN=TDNNF,RESOURCE=RELEASE;
#/ASSIGN OEFN=TDIF,RESOURCE=RELEASE;
#/ASSIGN OEFN=TDNAF,RESOURCE=RELEASE;
unset JOLSF
unset JSTR 
unset JNIF 
unset OKJF 
unset TDNWF
unset TDNNF
unset TDIF 
unset TDNAF
if($JRCODE == 255) then
  goto ENDJOB
endif
if($ABORT == 1) then
  goto ENDJOB
endif
set ABORT=0;
../exec/JTN00U $USER_ID $JRCODE 2 0 1
source ../job/CRC_LIBRARY.sh
if($JRCODE == 255) then
  goto ENDJOB
endif
if($ABORT == 1) then
  goto ENDJOB
endif
ENDJOB:
