#!/bin/tcsh
source ../job/RC_INIT.sh
set ABORT=0;
../exec/JTN00U $USER_ID $JRCODE 1 1 1
source ../job/CRC_LIBRARY.sh
if($JRCODE == 255) then
  goto ENDJOB
endif
if($ABORT == 1) then
  goto ENDJOB
endif
#/ASSIGN OEFN=JOLSF,EFN=JOLSF-TAM;
#/ASSIGN OEFN=JSTR,EFN=JSTR-TAM;
#/ASSIGN OEFN=JNIF,EFN=JNIF-TAM;
#/ASSIGN OEFN=OKJF,EFN=OKJF-TAM;
#/ASSIGN OEFN=TDNWF,EFN=TDNWF-TAM;
#/ASSIGN OEFN=TDNNF,EFN=TDNNF-TAM;
#/ASSIGN OEFN=TDIF,EFN=TDIF-TAM;
set ABORT=0;
../exec/JK020U-TAM $USER_ID $JRCODE 0
source ../job/CRC_LIBRARY.sh
#/ASSIGN OEFN=JOLSF,RESOURCE=RELEASE;
#/ASSIGN OEFN=JSTR,RESOURCE=RELEASE;
#/ASSIGN OEFN=JNIF,RESOURCE=RELEASE;
#/ASSIGN OEFN=OKJF,RESOURCE=RELEASE;
#/ASSIGN OEFN=TDNWF,RESOURCE=RELEASE;
#/ASSIGN OEFN=TDNNF,RESOURCE=RELEASE;
#/ASSIGN OEFN=TDIF,RESOURCE=RELEASE;
if($JRCODE == 255) then
  goto ENDJOB
endif
if($ABORT == 1) then
  goto ENDJOB
endif
set ABORT=0;
../exec/JTN00U $USER_ID $JRCODE 1 0 1
source ../job/CRC_LIBRARY.sh
if($JRCODE == 255) then
  goto ENDJOB
endif
if($ABORT == 1) then
  goto ENDJOB
endif
#**
#/ASSIGN OEFN=JOLSF,EFN=JOLSF-TAM;
#/ASSIGN OEFN=JOLJF,EFN=JOLJF-TAM;
#/ASSIGN OEFN=JSTR,EFN=JSTR-TAM;
#/ASSIGN OEFN=JNIF,EFN=JNIF-TAM;
#/ASSIGN OEFN=OKJF,EFN=OKJF-TAM;
#/ASSIGN OEFN=TDNWF,EFN=TDNWF-TAM;
#/ASSIGN OEFN=TDNNF,EFN=TDNNF-TAM;
#/ASSIGN OEFN=TDI-RDB,EFN=TDIF-TAM;
#/ASSIGN OEFN=TDNAF,EFN=TDNAF-TAM;
set ABORT=0;
../exec/JK041R-TAM $USER_ID $JRCODE 9
source ../job/CRC_LIBRARY.sh
#/ASSIGN OEFN=JOLSF,RESOURCE=RELEASE;
#/ASSIGN OEFN=JOLJF,RESOURCE=RELEASE;
#/ASSIGN OEFN=JSTR,RESOURCE=RELEASE;
#/ASSIGN OEFN=JNIF,RESOURCE=RELEASE;
#/ASSIGN OEFN=OKJF,RESOURCE=RELEASE;
#/ASSIGN OEFN=TDNWF,RESOURCE=RELEASE;
#/ASSIGN OEFN=TDNNF,RESOURCE=RELEASE;
#/ASSIGN OEFN=TDI-RDB,RESOURCE=RELEASE;
#/ASSIGN OEFN=TDNAF,RESOURCE=RELEASE;
if($JRCODE == 255) then
  goto ENDJOB
endif
if($ABORT == 1) then
  goto ENDJOB
endif
ENDJOB:
